import type { Species, SpeciesStats } from "../types/species";

export const mockSpecies: Species[] = [
  {
    id: "1",
    commonName: "Arara-Azul",
    scientificName: "Anodorhynchus hyacinthinus",
    category: "Bird",
    latitude: -15.7801,
    longitude: -47.9292,
    location: "Pantanal",
    observationDate: "2023-10-12",
    status: "Endangered",
    uniqueIdentifier: "SPQ-2023-B-0001",
    notes: "Observed near nesting sites in the Pantanal wetlands.",
  },
  {
    id: "2",
    commonName: "Vitória-Régia",
    scientificName: "Victoria amazonica",
    category: "Plant",
    latitude: -3.119,
    longitude: -60.0217,
    location: "Amazon Basin",
    observationDate: "2023-11-05",
    status: "Active",
    uniqueIdentifier: "SPQ-2023-P-0002",
    notes: "Large population found in Igapó forest flooded areas.",
  },
  {
    id: "3",
    commonName: "Pirarucu",
    scientificName: "Arapaima gigas",
    category: "Fish",
    latitude: -3.7327,
    longitude: -62.2138,
    location: "Araguaia River",
    observationDate: "2023-09-28",
    status: "Inactive",
    uniqueIdentifier: "SPQ-2023-F-0003",
    notes: "One of the largest freshwater fish in the world.",
  },
  {
    id: "4",
    commonName: "Onça-Pintada",
    scientificName: "Panthera onca",
    category: "Mammal",
    latitude: -15.601,
    longitude: -56.098,
    location: "Cerrado Reserve",
    observationDate: "2023-12-01",
    status: "Inactive",
    uniqueIdentifier: "SPQ-2023-M-0004",
    notes: "Camera trap sighting at dawn near water source.",
  },
  {
    id: "5",
    commonName: "Tucunaré-Açu",
    scientificName: "Cichla temensis",
    category: "Fish",
    latitude: -3.119,
    longitude: -60.0217,
    location: "Amazon Basin",
    observationDate: "2023-10-24",
    status: "Active",
    uniqueIdentifier: "SPQ-2023-F-0492",
    notes: "Abundant in black water rivers of the Amazon basin.",
  },
  {
    id: "6",
    commonName: "Ipê-Amarelo",
    scientificName: "Handroanthus albus",
    category: "Plant",
    latitude: -15.7801,
    longitude: -47.9292,
    location: "Cerrado",
    observationDate: "2023-10-18",
    status: "Active",
    uniqueIdentifier: "SPQ-2023-P-0006",
    notes: "National flower of Brazil. Common in Cerrado biome.",
  },
  {
    id: "7",
    commonName: "Boto-Cor-de-Rosa",
    scientificName: "Inia geoffrensis",
    category: "Mammal",
    latitude: -3.4168,
    longitude: -65.8561,
    location: "Negro River",
    observationDate: "2023-08-15",
    status: "Endangered",
    uniqueIdentifier: "SPQ-2023-M-0007",
    notes: "Pink river dolphin. Endemic to Amazon and Orinoco basins.",
  },
  {
    id: "8",
    commonName: "Caimão-do-Pantanal",
    scientificName: "Caiman yacare",
    category: "Reptile",
    latitude: -18.9187,
    longitude: -57.4278,
    location: "Pantanal",
    observationDate: "2023-07-20",
    status: "Active",
    uniqueIdentifier: "SPQ-2023-R-0008",
    notes: "Estimated 10 million individuals in the Pantanal.",
  },
  {
    id: "9",
    commonName: "Araçari-Mulato",
    scientificName: "Pteroglossus aracari",
    category: "Bird",
    latitude: -1.4558,
    longitude: -48.5044,
    location: "Marajó Island",
    observationDate: "2023-06-10",
    status: "Active",
    uniqueIdentifier: "SPQ-2023-B-0009",
  },
  {
    id: "10",
    commonName: "Surubim",
    scientificName: "Pseudoplatystoma corruscans",
    category: "Fish",
    latitude: -20.4428,
    longitude: -54.6461,
    location: "Solimões River",
    observationDate: "2023-05-05",
    status: "Inactive",
    uniqueIdentifier: "SPQ-2023-F-0010",
  },
];

export const mockStats: SpeciesStats = {
  total: 1248,
  byCategory: {
    Bird: 432,
    Fish: 385,
    Plant: 431,
    Mammal: 215,
    Reptile: 142,
    Other: 78,
  },
  quarterlyData: [
    { quarter: "Q1", birds: 180, fish: 120, plants: 160, mammals: 80 },
    { quarter: "Q2", birds: 210, fish: 150, plants: 200, mammals: 95 },
    { quarter: "Q3", birds: 250, fish: 130, plants: 190, mammals: 110 },
    { quarter: "Q4", birds: 200, fish: 160, plants: 180, mammals: 100 },
  ],
};
